name: Test
on:
  push:

jobs:
  action-path:
    runs-on: ubuntu-latest
    steps:
      - uses: jsoref/show-action-path@main
  action-subpath:
    runs-on: ubuntu-latest
    steps:
      - uses: jsoref/show-action-path/test@main
  local-path:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
  local-subpath:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./test
