name: Test
on:
  push:

jobs:
  test:
    strategy:
      matrix:
        path:
        - jsoref/show-action-path@main
        - jsoref/show-action-path/test@main
        - ./
        - ./test
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      if: contains(matrix.path, './')
      uses: actions/checkout@v3
    - name: report
      uses: ${{ matrix.path }}
